# Generated by Django 4.0 on 2021-12-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_bio',
            field=models.TextField(blank=True, max_length=250, verbose_name='Short Bio'),
        ),
    ]
