# Generated by Django 4.0 on 2021-12-23 21:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio_customuser_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.get_profile_picture_filepath, verbose_name='profile picture'),
        ),
    ]
