# Generated by Django 4.0 on 2021-12-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activation',
            new_name='OtpCode',
        ),
    ]
